#!/usr/bin/env python3
#!-*- utf-8 -*-

import sys
import math
from helper import helper

ac = len(sys.argv)

def main():
    if ac == 2 and sys.argv[1] == "-h":
        helper()
    if (ac > 2):
        print("too many parameters")
        sys_exit(84)

if __name__ == '__main__':
    main()
    sys_exit(0)